### ISSUE TITLE
Turkish Language Support

### ISSUE THREAD

**Issue by ilkmon** [RaiDrive/Translation#135]
I have used your program and like it. Decided to make a translation and its here. If you will add, ı will be happy. :)

[StringDictionary.tr.xaml.zip](https://github.com/RaiDrive/Translation/files/3726453/StringDictionary.tr.xaml.zip)

**Comment by Stanly5** [comment]
@ilkmon 
Thank you so much for your decision and contribution! It is great helps for us. And your kind comments on this xaml file.
I made simple syntax correction and upload your file. However we really prefer to record your contribution in Github as contributor. For that please make simple improvement and issue the "Pull request".  Candidate will be some answer for your question.

- Unknown space : for some storage Raidrive could not figure out the volume of storage. In this case you can see this message
![image](https://user-images.githubusercontent.com/39616295/66840177-9bd9e680-efa2-11e9-849f-c92de3165722.png)

For your other questions,
- Invalid Client : I will check about it to our engineering team and update you again.
- Send Opinion : sending your comments
- Code : I will check to our engineering team and update you again.

If you need helps how to edit and do "Pull request", please see following instruction.
https://help.github.com/articles/editing-files-in-another-user-s-repository/
If you need more help for this, please let me know.

For your information, you can apply your Turkish xaml file to Raidrive Setting/language with open icon. However you should use the downloaded file from Github because your original file has syntax error.

Thank you again!

**Comment by ilkmon** [comment]
Thanks @Stanly5
I'm new on github. So ı have done wrong first time tried and coudnt done in this repo.Because looks like I copied it inside to my repo and openned the request inside copy.  This time I have done it right.(I Wish.)

I'm waiting your explations about other missing words. When they are available, I'll be translated asap.

**Comment by Stanly5** [comment]
Thank you so much @ilkmon ,

Your pull request was merged. 
These are additional explanation for your question.
- Code : usage is like this example, error "code".
- Unmanaged domain by Active Directory : this is error message for one drive, but I also cannot fully understand what Active Directory is, even hear from engineering team. However domain means ip, and means domain should be managed by Active Directory, but it cannot be. It's what I explain about it. So please translate as it is, or just remain in English. 

Anyhow we have a campaign for contributors, so please review below message and send email to us.

===============================
Hello Contributors!
We are always appreciate your great contribution for the Translation of RaiDrive and we are happy to announce to start subscription plan for the RaiDrive professional edition which has wonderful features in early of July. To celebrate this release, we'd like to give you a small gift for your efforts so please send "support@raidrive.com" an email with your email address, and your github ID, and then we will let you know the details again by email.
Thank you so much, and please keep seeing our improvement!
Have a great day!

===============================

**Comment by ilkmon** [comment]
@Stanly5 could you ask when those words are using at V1.9.0 ?
"bucket, tenant"

**Comment by ilkmon** [comment]
Think, we have done Turkish translations for v1.9.0. You're doing it nice and simple just continue and let me know, when you need any help, I will be here.

**Comment by Stanly5** [comment]
@ilkmon ,
Thank you so much for your contribution and interest of RaiDrive. And I heard team sent you a small gift, so I hope you received it without any problem.
Please keep helping us whenever we need. Have a great day~
