### ISSUE TITLE
Arabic translation 

### ISSUE THREAD

**Issue by Mugahedb** [RaiDrive/Translation#3]
I would like to volunteer in translation to  Arabic language

**Comment by Mugahedb** [comment]
You are correct. 
Arabic is written from right to left. Words/sentences length might be long but a workaround is to use the suitable synonyms. Most operating systems today support Arabic without problems.
For the translation, as I understand, I should download a template file ex:"StringDictionary.en.xaml" and replace the required fields with Arabic translation. Please correct me if I'm wrong.

**Comment by gunnoh** [comment]
@Mugahedb Thanks for your advice. I'm not sure my question is too silly or not, but I don't have any experience of Arabic, so please kindly advise me again.
Because RaiDrive is designed for the language which is written from left to right, so with just word replacement, it can look awkward. How about other software? For example, menu placement, sentence alignment, and etc.
I hope just translated replacement is enough that people is using without awkwardness.
Please advise me.

StringDictionary.ar.xaml which is Arabic language file is added on GitHub, RaiDrive/Translation.
How to create pull request,
- Click Fork in RaiDrive/Translation, then created Mugahedb/Translation which is clone of RaiDrive/Translation.
- You can edit StringDictionary.ar.xaml in Mugahedb/Translation directly in Web, or you can download files with click "Clone or download" button, or you can use "github desktop" for downloading. After downloading you can edit it in your local desktop.
- Translation is working with replacement on StringDictionary.ar.xaml. For example, <system:String x:Key="Settings">__Settings__</system:String> --> <system:String x:Key="Settings">إعدادات</system:String>
- After completion, you can upload translated file to Mugahedb/Translation first with click "Upload files".
- After you check everything is ok, then you can create Pull Request, with click "New pull request". And then you can see "base fork:RaiDrive/Translation, base:master <- head fork:Mugahedb/Translation, base:master", and also can check your changes.
Click Create Pull Request, write comments, and then create pull request.
- These are what how to work pull request.
If you have any question, please leave a message.

**Comment by Stanly5** [comment]
@Mugahedb Thanks for your advice. I'm not sure my question is too silly or not, but I don't have any experience of Arabic, so please kindly advise me again.
Because RaiDrive is designed for the language which is written from left to right, so with just word replacement, it can look awkward. How about other software? For example, menu placement, sentence alignment, and etc.
I hope just translated replacement is enough that people is using without awkwardness.
Please advise me.

StringDictionary.ar.xaml which is Arabic language file is added on GitHub, RaiDrive/Translation.
How to create pull request,

- Click Fork in RaiDrive/Translation, then created Mugahedb/Translation which is clone of RaiDrive/Translation.
- You can edit StringDictionary.ar.xaml in Mugahedb/Translation directly in Web, or you can download files with click "Clone or download" button, or you can use "github desktop" for downloading. After downloading you can edit it in your local desktop.
- Translation is working with replacement on StringDictionary.ar.xaml. For example, <system:String x:Key="Settings">Settings</system:String> --> <system:String x:Key="Settings">إعدادات</system:String>
- After completion, you can upload translated file to Mugahedb/Translation first with click "Upload files".
After you check everything is ok, then you can create Pull Request, with click "New pull request". And then you can see "base fork:RaiDrive/Translation, base:master <- head fork:Mugahedb/Translation, base:master", and also can check your changes.
- Click Create Pull Request, write comments, and then create pull request.
These are what how to work pull request.
If you have any question, please leave a message.

**Comment by Mugahedb** [comment]
@Stanly5; Thank you for the instructions. I've uploaded the Arabic translation. Can you build a test version with Arabic translation to test its rendering.

**Comment by Stanly5** [comment]
@Mugahedb 
I appreciate your contribution, and it is merged and you can find your file in master branch now.
I will update you when test version is ready to check its rendering.

As already I left a message on pull request page, I found 2 sentences are not translated in your file, and I thought that's because meaning is not clear, so I would add some explanation. Further update should be appreciated.

- "Please press button, RaiDrive will be alive."
When RaiDrive service is stopped,
![raidrive will be alive](https://user-images.githubusercontent.com/39616295/42608843-abc9f9a2-85c4-11e8-964b-b10aab987d9b.png)
and then press the icon(red human)
![revive raidrive](https://user-images.githubusercontent.com/39616295/42608885-eeea5a24-85c4-11e8-996e-dc9eb0ee2322.png)

- "{0} free of {1} {2}"
{1} is total volume of storage, {0} is current free space. {2} is not used now. These will be replaced to detected volume.
For example, if {1} is 5.00GB, and {0} is 4.01GB, then "__4.01GB free of 5.00GB__"
![free of](https://user-images.githubusercontent.com/39616295/42613677-34c9bc52-85dd-11e8-99fd-94c77c90ee23.png)

**Comment by Mugahedb** [comment]
@Stanly5 
The two missing sentences are translated now. I've created a new pull request.
Thank you

**Comment by Stanly5** [comment]
@Mugahedb 
Thank you so much for your contribution again.
I'd like to ask you some question about Arabic. Please give me your advice.

It's the results from your advice. 
![new main](https://user-images.githubusercontent.com/39616295/42730940-ad471c44-883d-11e8-8af3-5d754521790d.png)

And below is the screen shot of Arabic OS.
![screen shot of arabic os](https://user-images.githubusercontent.com/39616295/42730947-eac74e5e-883d-11e8-9420-4e0a548142dc.png)

We'd like to follow the same expression as OS. 
Normally number and GB is also translated on it?
Could you give me an advice if it is follow the same expression then how to be modified?

{0} متاح من {1} {2}

Of course, for that, {1}, {0} should be changed as well, but that should be our another work.

**Comment by Stanly5** [comment]
@Mugahedb 
Could you please give me your advice for below version which is written right to left whether it is more comfortable or not?
We'd like to follow traditional Arabic rendering as well.

![settings](https://user-images.githubusercontent.com/39616295/42990057-8d64dd1e-8c3c-11e8-9dd7-994e29e701f1.png)
![main](https://user-images.githubusercontent.com/39616295/42990059-9202a22a-8c3c-11e8-825a-4a8e3a16af1b.png)
![adding sftp](https://user-images.githubusercontent.com/39616295/42990109-b734147a-8c3c-11e8-9d81-4465c88fa35a.png)
![adding ftp](https://user-images.githubusercontent.com/39616295/42990114-ba333110-8c3c-11e8-91df-9627f79c5e80.png)
