### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by RemboIII** [RaiDrive/Translation#31]
Hey!
I'd like to provide a Dutch (Nederlands) translation. 
Please let me know how and when to help!

Best regards, 
Remco.

**Comment by Stanly5** [comment]
Thank you so much for your interests!
I added "StringDictionary.nl.xaml" files which is based on English.
You can change below **_bold & Italic_** from English to Dutch for the translation on the xaml file, 
...
	<system:String x:Key="Settings">**_Settings_**</system:String>
	<system:String x:Key="Settings.Header">**_Settings_**</system:String>
	<system:String x:Key="Settings.General">**_General_**</system:String>
...
After translation, please use "Pull Request" for the apply.
FYI, you can refer to the https://github.com/RaiDrive/Translation/wiki as well.
If you are not familiar with this GitHub process, then please leave a message.

**Comment by Stanly5** [comment]
@RemboIII 
Thank you so much for your contribution!

At first, you can test your translation with the version 1.4.0 through the load your file. But during my testing RaiDrive was down. I think it will be what you mentioned "doesn't change anything in the interface. Its because syntax error and it is caused by special character **_"&"_** in line **_#106_**. It cannot be interpreted properly.

> **_IE10 & IE11 should be revised IE10, IE11._**

After that, you can find everything works well. I already confirmed.

However I found something strange in your file, 
line#41 (Priv�sleutel), 
line#67 (Kies een priv�sleutelbestand), 
line#105 (Het stuurprogramma is niet ge�nstalleerd. Installeer RaiDrive opnieuw.)
I'm not sure it is same on your side, but please check it again.

Through the "Pull Request" process, contributor can be specified in GitHub so that people can know who is contributor, and we'd like to keep this record. Therefore even it is little bit bothering you, but please use this "Pull Request" process.

Please see below step and follow.

- In your RemboIII/translation repository, choose "**<>Code**" tab. (upper left)
- You can find and Click "**Upload files**" right upper
- Upload the file with dragging your local "**StringDictionary.nl.xaml**" file to the area, writing comments on the box just below "**Commit changes**", and then press the green "**Commit changes**" button.
- You can confirm everything is well on StringDictionary.nl.xaml with click the file.
- For the pull request, choose"**Pull requests**" tab (just right side of <>Code), and press the green "**New pull request**" button.
- GitHub automatically checks what's the difference, and will show 1 changed file which is StringDictionary.nl.xaml. Please double check base fork:RaiDrive/Translation master, <- head fork: RemboIII/translation master. And then press the green "Create pull request".
- Writing the title and comments, and then press the green "**Create pull request**" button.

After above step, I can get your pull request, and after merge your pull request, it will be applied main file on RaiDrive Translation repository, and you are registered on our contributors.
Even it is a little bit troublesome you think, please follow our guidance. If you have any problem to do it, please leave a message.
Thank you so much for your contribution again!

**Comment by RemboIII** [comment]
After I removed the special characters, the translation file was functional in the program. However, those diacritics are quite common in many European languages. Could the character set be changed or expanded?
I tried to upload the file according to your instruction, but I don't appear to have sufficient rights: "Uploads are disabled. File uploads require push access to this repository.".

**Comment by Stanly5** [comment]
@RemboIII 
For using "&" in xaml file, you can use  `"&amp;"` instead of "&" in xaml file.
`"IE10 &amp; IE11"` should be ok.

Regarding the upload the file, I think you have tried it on RaiDrive/Translation repository. 
Could you please try again in your repository, RemboIII/translation?

If you still have an issue, please leave a message again.

**Comment by Stanly5** [comment]
@RemboIII 
Hello,
Still do you have a problem to upload and pull request?
If yes, please let me know about it.
If you prefer that I just update your translation in here without keeping record of your contribution, then I can do it.
Thank you so much for your interests.
