### ISSUE TITLE
Hungarian

### ISSUE THREAD

**Issue by lostprophet** [RaiDrive/Translation#49]
Hi! I would love to help out with the Hungarian translation.

**Comment by Stanly5** [comment]
Hello~
Thank you so much for your interests and contribution.
Hungarian language code is "hu", and I will intialize "StringDictionary.hu.xaml" file by tomorrow.
If you want to start before that, you can download "StringDictionary.en.xaml" and re-name it to  "StringDictionary.hu.xaml" and modify from "en" to "hu" in the file.
<system:String x:Key="Current.Language">en</system:String> --> <system:String x:Key="Current.Language">hu</system:String>

Have a great day~

**Comment by Stanly5** [comment]
Hi!,
I initialized StringDictionary.hu.xaml for Hungarian, you can find it on Code tab.
Please help us Hungarian translation.
Thank you so much.

**Comment by lostprophet** [comment]
I'm not very familiar with GitHub. What would be the best way to do the translation? Just download the .xaml file, translate it, and where should I upload it?

**Comment by Stanly5** [comment]
@lostprophet 
Hello~
There are several way to issue "Pull Request".

First, you can edit "StringDictionary.hu.xaml" in this GitHub. I can find you are editing it but not completed. In this case after complete the translation in your lostprophet/translation, Commit it. And then you can find "Create Pull Request" which is green button. Please refer to the Wiki ( https://help.github.com/articles/editing-files-in-your-repository/)

Second, you can download "StringDictionary.hu.xaml" and then edit it in your local laptop and uploading like below.

- In your lostprophet/translation repository, choose "<>Code" tab. (upper left)
- You can find and Click "Upload files" right upper
- Upload the file with dragging local "StringDictionary.hu.xaml" file to the area, writing comments on the box just below "Commit changes", and then press the green "Commit changes" button.
- You can confirm everything is well on StringDictionary.hu.xaml with click the file.
- For the pull request, choose"Pull requests" tab (just right side of <>Code), and press the green "New pull request" button.
- GitHub automatically checks what's the difference, and will show 1 changed file which is StringDictionary.hu.xaml. Please double check base fork:RaiDrive/Translation master, <- head fork: lostprophet/translation master. And then press the green "Create pull request".
Writing the title and comments, and then press the green "Create pull request" button.

After above step, I can get your pull request, and after merge your pull request, it will be applied main file on RaiDrive Translation repository, and you are registered on our contributors.

Third, you can make zip file for "StringDictionary.hu.xaml" and then dragging & dropping it in this issue page. I can follow up the pull request instead of you, but in this case your contribution is not recorded.

If you have further question, please leave a message again.

**Comment by lostprophet** [comment]
I think I did it right. Can you check?

**Comment by Stanly5** [comment]
@lostprophet
Thank you so much for your  wonderful contribution!
I checked you translated it, but I don't have any ability to the Hungarian translation.

Next step should be "Create Pull Request".
In your lostprophet/translation repository, 
- Select patch-2 which you completed to translate among the branches.
- Click the new pull request
- confirm RaiDrive/Translation <- lostprophet/Translation
- Click create pull request

After following these up, I can merge your translation in RaiDrive/Translation. Please help us, it is almost done.
Thanks again.

**Comment by Stanly5** [comment]
@lostprophet 
I confirmed your StringDictionary.hu.xaml was merged and works well in RaiDrive.
Thank you so much for your great contribution!
